cluster_name: pczarkow

rosa_private_link: true
# note private-link forces private to be true
# regardless of the following value.
rosa_private: false
rosa_sts: true
rosa_multi_az: true
rosa_vpc_endpoints_enabled: true
# uncomment to pin to a version
# rosa_version: 4.13.10
rosa_region: us-east-1
rosa_vpc_cidr: "10.0.0.0/16"
rosa_vpc_public_subnets: []
rosa_compute_machine_type: m5.xlarge

rosa_tgw_enabled: true
# The full cidr that encompasses all VPCs the TGW will be
# attached to.
rosa_tgw_cidr: "10.0.0.0/8"

rosa_egress_vpc_enabled: true
rosa_egress_vpc_multi_az: true
# defaults file for roles/vpc
rosa_egress_vpc_cidr: "10.10.0.0/16"

jumphost_instance_type: t2.small

proxy_enabled: true

rosa_create_admin: true
rosa_custom_domain_enabled: false
rosa_custom_domain_vars:
  name: custom-domain
  namespace: custom-domain
  fqdn: apps.example.com # *.apps.example.com

## don't set these and let it use your already logged in accounts
# aws_access_key_id:
# aws_secret_access_key:
# aws_default_region:
# rosa_token:

# uncomment to enable custom kms workflow
# rosa_kms_key_arn: "" #arn:aws:kms:us-east-2:<redacted>:key/<redacted>

extra_tags:
  cost-center: CC468
  service-phase: lab
  app-code: MOBB-001
  owner: "{{ ansible_user_id }}@redhat.com"
