---
# tasks file for roles/account-roles

- name: create support role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Support-Role"
    assume_role_policy_document: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_support_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: 'true'
      rosa_role_type: support
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      create_instance_profile: false

- name: create support policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles.prefix }}-Support-Role"
    policy_name: "{{ rosa_account_roles.prefix }}-Support-Role-Policy"
    policy_json: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_support_permission_policy.json')|path_join) }}"

- name: create installer role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Installer-Role"
    assume_role_policy_document: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_installer_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: 'true'
      rosa_role_type: installer
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      create_instance_profile: false

- name: create installer policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles.prefix }}-Installer-Role"
    policy_name: "{{ rosa_account_roles.prefix }}-Installer-Role-Policy"
    policy_json: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_installer_permission_policy.json')|path_join) }}"

- name: create controlplane role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-ControlPlane-Role"
    assume_role_policy_document: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_instance_controlplane_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: 'true'
      rosa_role_type: instance_controlplane
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      create_instance_profile: false

- name: create controlplane policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles.prefix }}-ControlPlane-Role"
    policy_name: "{{ rosa_account_roles.prefix }}-ControlPlane-Role-Policy"
    policy_json: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_instance_controlplane_permission_policy.json')|path_join) }}"

- name: create worker role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Worker-Role"
    assume_role_policy_document: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_instance_worker_trust_policy.json')|path_join) }}"
    tags:
      red-hat-managed: 'true'
      rosa_role_type: instance_worker
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      create_instance_profile: false

- name: create worker policy
  iam_policy:
    iam_type: role
    iam_name: "{{ rosa_account_roles.prefix }}-Worker-Role"
    policy_name: "{{ rosa_account_roles.prefix }}-Worker-Role-Policy"
    policy_json: "{{ lookup('file',('classic',rosa_account_roles.version,'sts_instance_worker_permission_policy.json')|path_join) }}"

# - fail:
