- fail:
  when: rosa_account_roles.prefix is not search("^.*-HCP-ROSA$")

- name: create support role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Support-Role"
    assume_role_policy_document: "{{ lookup('file',('hcp',rosa_account_roles.version,'sts_support_trust_policy.json')|path_join) }}"
    managed_policies: ["arn:aws:iam::aws:policy/service-role/ROSASRESupportPolicy"]
    create_instance_profile: false
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      rosa_role_type: "support"

- name: create installer role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Installer-Role"
    assume_role_policy_document: "{{ lookup('file',('hcp',rosa_account_roles.version,'sts_installer_trust_policy.json')|path_join) }}"
    managed_policies: ["arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy"]
    create_instance_profile: false
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      rosa_role_type: "installer"

- name: create worker role
  iam_role:
    name: "{{ rosa_account_roles.prefix }}-Worker-Role"
    assume_role_policy_document: "{{ lookup('file',('hcp',rosa_account_roles.version,'sts_instance_worker_trust_policy.json')|path_join) }}"
    managed_policies: ["arn:aws:iam::aws:policy/service-role/ROSAWorkerInstancePolicy"]
    create_instance_profile: false
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_managed_policies: "true"
      rosa_openshift_version: "{{ rosa_account_roles.version }}"
      rosa_role_prefix: "{{ rosa_account_roles.prefix }}"
      rosa_role_type: "instance_worker"
