---
- name:         "init"
  hosts:        localhost
  connection:   local
  gather_facts: true
  tags:
    - always

  tasks:
    - name: "set a state fact"
      ansible.builtin.set_fact:
        state: absent

    - ansible.builtin.set_fact:
        ansible_python_interpreter: ./virtualenv/bin/python
        staging_dir: "{{ playbook_dir }}/staging"

    - name: "get the aws account id"
      aws_caller_info:
      register: _aws_caller_info

    - ansible.builtin.set_fact:
        aws_account_id: "{{ _aws_caller_info.account }}"

- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/_vars

    - name: roles/rosa_cluster
      vars:
        rosa_cluster:
          name: "{{ cluster_name }}"
          aws_account_id: "{{ aws_account_id }}"
          account_roles_prefix: "{{ rosa_account_roles_prefix }}"
          region: "{{ rosa_region }}"
          hosted_cp: "{{ rosa_hosted_cp }}"

    - name: roles/rosa_account_roles
      vars:
        rosa_account_roles:
          hosted_cp: "{{ rosa_hosted_cp }}"
          version: "{{ rosa_account_roles_version }}"
          prefix: "{{ rosa_account_roles_prefix }}"

    - name: roles/rosa_ec2_instance
      vars:
        rosa_ec2_instance:
          name: "rosa-{{ cluster_name }}-jumphost"
          region: "{{ rosa_region }}"
      when:
        - (rosa_private or rosa_private_link) or
          (enable_jumphost | default(False) | bool)

    - name: roles/rosa_ec2_instance
      vars:
        rosa_ec2_instance:
          name: "rosa-{{ cluster_name }}-proxy"
          region: "{{ rosa_region }}"
      when:
        - (rosa_private_link | bool) and
          (proxy_enabled | default(False) | bool)

    - name: roles/rosa_transit_gateway
      vars:
        rosa_transit_gateway:
          name: "rosa-{{ cluster_name }}-tgw"
          region: "{{ rosa_region }}"
      when: rosa_tgw_enabled | bool

    - name: roles/rosa_egress_vpc
      vars:
        rosa_egress_vpc:
          name: "rosa-{{ cluster_name }}-egress-vpc"
          region: "{{ rosa_region }}"
      when:
        - rosa_egress_vpc_enabled | bool
        - rosa_egress_vpc_subnet_ids | default([]) | length == 0

    # ROSA VPC
    - name: roles/rosa_vpc
      vars:
        rosa_vpc:
          name: "rosa-{{ cluster_name }}-vpc"
          region: "{{ rosa_region }}"
      when: rosa_subnet_ids | default([]) | length == 0
