- set_fact:
    _name: "{{ '-'.join([cluster_name,item.namespace,item.name])[:64] }}"
#     when: _cluster_type == 'classic'
# - set_fact:
#     _name: "{{ '-'.join([cluster_name, 'hcp', item.namespace,item.name])[:64] }}"
#     when: _cluster_type == 'hcp'

- name: "delete operator policy {{ _name }}"
  iam_policy:
    iam_type: role
    iam_name: "{{ _name }}"
    policy_name: "{{ _name }}"
    state: absent
  register: _delete
  failed_when: ('error' in _delete.keys()) and (_delete.error.code != 'NoSuchEntity')
  when: _cluster_type == 'classic'

- name: "delete operator role {{ _name }}"
  iam_role:
    name: "{{ _name }}"
    state: absent

- name: "delete instance profile {{ _name }}"
  amazon.aws.iam_instance_profile:
    name: "{{ _name }}"
    state: absent
