---
# defaults file for rosa_ec2_instance
rosa_ec2_instance:
  name: rosa-ec2-instance
  ami: "" # if left blank will pick latest RHEL 8 AMI based on the below pattern
  ami_name: "RHEL-8.*_HVM-*-x86_64-*Hourly*"
  ami_owner: "309956199498"
  instance_type: t2.small
  region: us-east-2
  user_data: # "{{ lookup('file', 'basic_user_data.sh') }}"
  user_data_template: ~
  assign_public_ip: false
  vpc_id:
  subnet_id:
  security_group_rules:
    - proto: tcp
      ports: [22]
      cidr_ip: 0.0.0.0/0
      rule_desc: allow ssh
  ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: {}
  # extra vars that can be set for templates
  template_vars: {}
